<?php

include_once "main.php";
$object = Singleton::getInstance();
//create a data base called career
$object->createDbt("userregistration");

//start the database
$conn = $object->startDB("userregistration");

//$object->insertIntoTableCareer($conn, "#accounting", "Accounting", " Accounting supplies quantitative information essential to management decision-making and control, as well as a wide variety of tax and consulting services and information on management's effective use of an organization's resources. This major helps prepare students for careers in public, industrial, or governmental accounting and also provides an appropriate background for those planning to enter law school or graduate school. Public accounting is carried on by independent practitioners, most of whom are certified public accountants.[BUSINESS]");

$object->insertIntoTableCareer($conn, "Actuarial Science", "An actuary is a business professional who uses mathematical skills to define, analyze, and solve business and social problems. Actuaries generally are employed in life, health, and casualty insurance companies, consulting firms, and government. [MATHEMATICAL SCIENCES]", "Physical science, Mathematics, English");

$object->insertIntoTableCareer($conn, "Advertising", " The advertising major attempts to explain why businesses and others use advertising as a form of communication: how advertising affects the mass media; how advertising is used by consumers in making buying decisions; how advertising is controlled and regulated; and what effects advertising has on the economy. People who work in advertising include artists, statisticians, writers, psychologists, sales people, researchers, designers, managers, accountants, planners, analysts, and others.[COMMUNICATION ARTS", "English");

$object->insertIntoTableCareer($conn, "Agriculture", " Agricultural graduates are an important link in the chain that provides people with a safe and abundant food supply. Students may focus their studies on animal production, field crops management, fruit and vegetable crops, management, turf management and business.[ENVIRONMENTAL RESOURCE MANAGEMENT", "Mathematics, Physical Science, English, Agricultural Science");

$object->insertIntoTableCareer($conn, "Aviation", " A program that focuses on the general study of aviation and the aviation industry,
including in-flight and ground support operations. Includes instruction in the technical, business, 
and general aspects of air transportation systems. Careere may include Pilot, Air traffic Controller, Aviation Maintanance Technician, Flight Engeneer,and Aircraft Mechanic.[AVIATION AND MANAGEMENT]", "Mathematics, Physical Science, English");


$object->insertIntoTableCareer($conn, "Agricultural and Biological Engineering", " This major helps prepare students for careers involving the application of engineering principles to agricultural and biological production systems, processing systems, and conservation of land and water resources. The curriculum may include food engineering, postharvest handling and processing of commodities, power and machinery development and applications, resource management and utilization, soil and water management, and structures and their environmental modifications. 
Careers for graduates include design, development, and research engineering positions involving food processing, machinery development, irrigation and drainage, soil and water conservation, materials handling, and structural systems for animals, plants, and crop storage. Agricultural and biological engineers are employed in industry, consulting firms, and governmental agencies in the United States and abroad. Graduates may deal with the various engineering aspects associated with production and processing of food, fiber, and other biological materials, within the constraints of environmental protection and natural resource conservation.[ENGINEERING]", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Agricultural Business Management", " The curriculum emphasizes using concepts and methods from economics and business management in identifying, analyzing, and solving management problems related to agriculture, natural resources, and economic development. The program provides a balance between applied economics and business management studies, with a limited amount of applied science. Examples of employment areas include finance and banking, management, input, commodity and food marketing, sales, administration, public and industrial relations, production management, economic and statistical analysis, managerial accounting, management information systems, and transportation.[AGRIBUSINESS AND ECONOMICS/ ENVIRONMENTAL RESOURCE MANAGEMENT/ BUSINESS]", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Agriculture Economics", "The undergraduate program provides students with tools to apply general economics to everyday agricultural businesses. Employment opportunities may involve such areas as management, sales, finance, government, public relations or personnel. Graduates can also pursue careers in the farm sector as owner operators or managers. Beyond the identified career areas, graduates of this program may complete advanced degrees in the discipline and in business and law schools.[AGRIBUSINESS AND ECONOMICS]", "Mathematics, Physical Science");
$object->insertIntoTableCareer($conn, "Animal Bioscience", " This major provides a strong background in those biological and physical sciences underlying contemporary animal agriculture and establishes a sound foundation for graduate-level study in animal and related sciences. Such disciplines may include animal behavior, genetics, nutrition, and physiology.<br />
The purpose of the Animal Bioscience major is to prepare students for admission to veterinary school and/or entry into graduate programs in animal biosciences. Students may prepare for graduate programs such as genetics, nutrition, microbiology, animal sciences, physiology, biochemistry, or others.[FOOD-LIFE SCIENCE/ SCIENCE]", "Mathematics, Physical Science");

$object->insertIntoTableCareer($conn, "Animal Sciences", "Animal Science may be defined as the study and integration of all disciplines that relate to the function and care of animals for the benefit of humankind by providing companionship, food, fiber, and research. The Animal Sciences major includes references to all types of animals.
The educational experiences included in this major should prepare the student for a wide range of entry-level positions in production, agriculture, agribusiness, and allied industries, as well as provide preparation for the pursuit of post-baccalaureate studies leading to professional or advanced degrees. The student is expected to develop a comprehensive understanding of the biological and physical sciences underlying the functioning of all types of animals. [FOOD-LIFE SCIENCE/ SCIENCE/ZOOLOGY]", "Mathematics, Physical Science, Life Science");

$object->insertIntoTableCareer($conn, "Anthropology", " Anthropology students study culture and cultural diversity throughout the world. The field is classically divided into four areas: social anthropology, the study of contemporary societies; archaeology, the study of the material remains of past societies; linguistics, the study of the structure and principles of language; and physical anthropology, the study of human evolution and biological diversity.
After graduating, some anthropology majors may pursue graduate degrees in specialized areas, preparing themselves for careers in teaching, research, or applied anthropology. Many students may enter educational fields and social services through teaching in the U.S. and abroad, joining the Peace Corps, or working in museums and on archaeological excavations. Others may go on to careers in law and medicine, aided by their knowledge of anthropological concepts such as cultural diversity and human evolution. Today, as our current era of global economics demands the appreciation of different cultural perspectives, more business opportunities are open to the anthropologist.[SOCIAL SCIENCE]", "English");

$object->insertIntoTableCareer($conn, "Applied Mathematics", "The applied mathematics major offers another option for students with quantitative skills and with an interest in a field outside of mathematics. Courses from the three disciplines of mathematics, statistics, and computer and information science are integrated to form a coherent undergraduate program. The major also includes a related field, such as economics, industrial and systems engineering, geological sciences, or insurance, in which quantitative methods are applied.[MATHEMATICAL SCIENCES] ", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Archaeology", "This interdisciplinary major combines the faculty and resources of several departments to create a program of study in prehistoric, historic, and classical archaeology. Majors gain a thorough grounding in archaeological method and theory, including the recovery, analysis, and interpretation of the material remains of past cultures and societies.
Upon graduation, many majors may pursue a professional career in archaeology, which typically requires an advanced degree. Many who wish to pursue field research opportunities before entering graduate school may find employment in archaeological resource management, a growing private industry in the environmental impact field. Others may find positions with government agencies and museums. Since archaeology is a liberal arts major that offers a unique merger of both humanistic and scientific thought, many majors draw upon this training in pursuing careers in medicine, law, and a range of other fields.[SOCIAL SCIENCE]", "English");

$object->insertIntoTableCareer($conn, "Architectural Engineering", " This major emphasizes the application of scientific and engineering principles to the planning, design, and construction of buildings and building systems. The goal of the program is to provide engineering graduates with the best education available for careers in the building professions. Graduates will have the ability to practice as registered professional engineers in a variety of areas, both public and private, related to the planning, design, construction, and operation of buildings and to assume a place of leadership in society.[ENGINEERING/ ART AND ARCHITECTURE]", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Architecture", " Architecture encompasses the making and study of the buildings and environment that we inhabit. 
The concerns of architecture involve a variety of areas of study, including the art of representing built projects through drawings and computer graphics; the technology of building structure, building materials, and natural and mechanical systems; the history, theory, and art of making, using, and understanding buildings as cultural artifacts for human use; and the practice of architecture in the context of urban form and business economics. The bachelor of science in architecture degree provides instruction in history, representation, design, theory, and technology, emphasizing the development of architecture as a language of form, space, and order. The undergraduate major establishes a strong design foundation that serves a variety of careers and provides flexibility as individual opportunities change. A master's degree in architecture is required to qualify for licensure.[ART AND ARCHITECTURE]", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Art History", " A painting, a sculpture, or a building is a monument surviving from the past, bearing the imprint of its creator and its time. Art history students learn to interpret these monuments, discovering their special characteristics and the value of the age in which they were created. This major provides students with the skills and perspectives of the liberal arts: to think clearly; to write well; and to find, analyze, evaluate, and present facts and ideas. Majors can also develop independent study projects, and most take several courses in studio art and architectural history.<br />
Many majors find that their humanistic background serves them well in disciplines such as law, business, and medicine. Others pursue graduate study to prepare themselves for careers in museums, in the art market, or in teaching, most often at the college level.", "English");

$object->insertIntoTableCareer($conn, "Studio Art", " Studio Art provides instruction in the visual arts by emphasizing the development of visual awareness and expression through hands-on involvement in the creative process. This program offers students practical instruction in drawing, painting, sculpture, printmaking, and photography. Courses generally increase in complexity and challenge, culminating in an individual exhibition of student's work just before graduation. After graduating, students may move on to graduate work in the fine arts. Others may want to pursue graduate work in graphic design, art therapy, museum work, medical illustration, and teaching.[ART AND ARCHITECTURE]", "English");

$object->insertIntoTableCareer($conn, "Art Education", "This major will likely offer two options: art education for schools, and art education for cultural and social agencies. An integral part of each option for students is a basic art studio, art history, art criticism, and aesthetics preparation.[EDUCATION/ART AND ARCHITECTURE] ", "English, Physical Science");

$object->insertIntoTableCareer($conn, "Biobehavioral Health", "This major provides interdisciplinary training designed to integrate biological, behavioral, and social science approaches to the study of human health and illness. Emphasis is placed on the study of physical health. The goal of this major is to help students gain working familiarity with multiple perspectives, approaches, and methods needed to address and solve problems of human health and illness. This major helps prepare graduates for entry-level jobs in a range of biomedical and health-related areas, including roles as research assistants, laboratory managers, biomedical product representatives, technical support positions in biomedical and health-related fields. This major also will provide excellent preparation for advanced study in natural and social science disciplines and related professional areas such as epidemiology, public health, environmental health and safety, and human services. [HEALTH SERVICES AND SCIENCES/ SCIENCE/ BEHAVIORAL SCIENCE] ", "Mathematics, Physical Science, English");

$object->insertIntoTableCareer($conn, "Biotechnology", "Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry.[SCIENCE] ");

$object->insertIntoTableCareer($conn, "Business Administration and Management", "Businesses, large and small, are coming to understand a new environment of rapid change. They are being challenged to take advantage of new markets and greater demands on current products. Their ability to adapt to a rapidly changing environment can yield great rewards, but it requires multifunctional and multitasking individuals able to form and develop new businesses and comfortably exist within a sea of change.
The management major with an emphasis in entrepreneurial studies is intended to provide current and future business professionals with the necessary skills and tools to successfully form and develop businesses. Students generally learn personal time, work, and life management skills. Students will also learn business leadership skills, management skills, skills for coping with a rapidly changing environment, communication, negotiation skills, and skills to assess risk and make sound business decisions within an unstructured environment.[BUSINESS] ", "Mathematics, Accounting");

$object->insertIntoTableCareer($conn, "Business Logistics", " A supply chain, or logistics network stretches from the source of raw material to the point of final consumption, involves multiple trading partners, and comprises business processes for acquiring materials and supplies, malting products, and delivering them to customers throughout the world. Business logistics focuses on the planning and coordination of product, information, and cash flows along the supply chain to achieve a vision of a market opportunity that is shared by all the trading partners. In addition, because transportation is one of the most vital services in modern society, the major gives special attention to the management and economics of domestic and international freight transportation systems and to government policies toward the performance of such systems.[BUSINESS]", "Accounting, MATHEMATICS");

$object->insertIntoTableCareer($conn, "Chemical Engineering", " >Chemical engineers process the food we eat and the fuels we burn, purify our water and air, and recover raw materials found on land, in the oceans, and-perhaps in the future-in space. They help produce the synthetic fibers in our clothing, the medications we need, and the materials that make up the everyday objects we use, from buildings to computer chips.[ENGINEERING/ SCIENCE]", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Chemistry", " Chemistry probes the fundamental concepts of nature and helps us understand the world around us. It deals with all substances at the molecular level: their composition, their properties, and how they are transformed into new substances. Chemistry is a central science of great importance to society. It provides a broad range of opportunities in many specialized fields, including biotechnology, polymer chemistry, environmental chemistry, materials chemistry, and medicine. After graduating with a bachelor's degree, many chemistry majors may go on to graduate or professional schools to pursue advanced degrees. Other graduates may find employment in industry, education, or government. [SCIENCE]", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Children", " Careers working with children can be served through a variety of methods such as an educator or a parent. One can also find a career in a daycare facility or as a caretaker from one's own home. Education varies based on the career.[HUMAN SERVICES]", "English");

$object->insertIntoTableCareer($conn, "Civil Engineering", "Civil engineers design, build, and maintain infrastructure. The undergraduate degree generally emphasizes a comprehensive grounding in the three major facets of civil engineering -structural, environmental, and transportation- while stressing the fundamentals of mathematics and the physical and engineering sciences. Because of the increasing interest in the rehabilitation and replacement of the nation's infrastructure and in cleaning up the environment, the job prospects for civil engineering graduates are excellent.[ENGINEERING] ", "PHYSICAL SCIENCE, MATHEMATICS, ENGLISH");

$object->insertIntoTableCareer($conn, "Computer Engineering", "This major includes coverage in breadth and depth of basic science, engineering, and abstract concepts of information handling. Students are generally prepared for careers in the design, analysis and use of hardware, software, and systems. The program is structured to ensure that graduates have a clear understanding of the design and the applications of computers, as well as the ability to apply this knowledge throughout their professional careers.[ENGINEERING/ COMPUTER SCIENCE] ", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Computer Science", "Computer Science is primarily concerned with the analysis, design, and applications of computing software and systems. It includes programming languages, data structures, compilers, operating systems, data bases, and artificial intelligence.[MATHEMATICAL SCIENCES/COMPUTER SCIENCE] ", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Crime, Law, and Justice", " This major provides students with a broadly based liberal education focused on the understanding and analysis of crime and justice systems. Students obtain a foundation of knowledge of the basic components of the criminal justice and legal systems as well as abilities to solve problems, think and read critically, and write effectively within the context of criminal justice and criminological research and theory.[SOCIAL SCIENCE]","MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Culinary", "A program that focuses on the blending of food science and the culinary arts and that prepares individuals to work as research chefs and related research and development positions in the food industry. Includes instruction in culinary arts, food chemistry, food safety and quality, food processing, nutrition, and business management. Possible jobs include Chef, Food journalist, Food stylist, Nutritionist, and Hospitality management[Culinary studies] ", "TOURISM, MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Dance", "Dance is a performance-oriented program designed to prepare students professionally as performers, choreographers, and teachers, as well as to prepare them for graduate study.[HEALTH, PHYSICAL EDUCATION, AND RECREATION/ PERFORMING ARTS] ", "PURE MAtHEMATICS OR MATHEMATICS LITERACY, ENGLISH");
$object->insertIntoTableCareer($conn, "Earth Sciences", "This major provides a comprehensive program in environmental sciences based on a strong emphasis in earth sciences. It is especially directed toward study of the problems that arise from the complex interaction of man's technological and social activities with the natural environment.<br />
Graduates are in demand for positions in government, industry, and consulting. Professional activities include gathering and evaluating data on environments; management and coordination of specialized programs in environmental control and modification; and industrial and government planning.[ENVIRONMENTAL RESOURCE MANAGEMENT] ", "GEOMETRY, PHYSICAL SCIENCE, LIFE SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Economics", " Economics' studies how individuals make choices in the face of scarcity. Whether dealing with how households determine what goods they buy, why firms produce certain quantities of goods and services, and what forces shape the aggregate performance of economic institutions. Economics is valuable not only for the topic it treats, but also for its rigorous methods of analysis.<br />
Economic majors often attend graduate school, law school or business school. Majors who choose to work immediately upon graduation may find employment in financial institutions, manufacturing corporations, consulting firms, and state and federal agencies. [BUSINESS]", "ACCOUNTING, ENGLISH");

$object->insertIntoTableCareer($conn, "Electrical Engineering", " Electrical engineering is the application of electrical science and technology to the needs of society. Areas of specialization may include antennas, communications, control systems, digital signal processing, electronic device fabrication and circuit design, energy conversion, fiber optics and lasers, image processing, microwaves and radar, optical computing, power systems, and remote sensing. Not only is the job market for electrical engineers very favorable, but opportunities for graduate study are abundant. Moreover, the rigorous nature of the curriculum of engineering makes it excellent preparation for advanced study and entry into a professional career in such fields as business, law, and medicine.[ENGINEERING]", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Elementary and Kindergarten Education", " This major offers teaching options in early childhood education and in elementary education (Kindergarten to Grade 6).[EDUCATION]", "ENGLISH");
$object->insertIntoTableCareer($conn, "Engineering Science", " In Engineering Science understanding of the basic engineering practices are combined with an in-depth knowledge of the fundamentals of the engineering sciences: electricity and magnetism, fluid and solid mechanics, mathematics, computer applications, materials, and thermodynamics and heat transfer. Graduates may choose to pursue graduate study either in biomedical engineering or medicine, or a career in one of the traditional engineering disciplines.[MATHEMATICAL SCIENCES/ENGINEERING/ SCIENCE]", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "English", "This major provides an opportunity to study human communication and artistic expression through literature language, writing, and theory. English majors learn to write clearly and effectively, think critically and analytically, and question the works and the world around them. While these skills are applicable to virtually any future career choice, most English majors apply to graduate school, law school and even medical school. Those who do not pursue graduate school find the study of English an excellent preparation for government service, business careers, international agencies, publishing, journalism, and secondary school teaching. [COMMUNICATION ARTS] ", "ENGLISH");
$object->insertIntoTableCareer($conn, "Environmental Systems Engineering", "Environmental Systems Engineering is an interdisciplinary program concerned with the sources and causes of industrial impact on the environment and the choice of appropriate remediation strategies. Students enrolled in the program acquire: a) a strong foundation in mathematics and the physical and engineering sciences, b) a fundamental background in the application of the earth and atmospheric sciences and the principles of process engineering to the environmental problems of the basic industries, especially those involved in the extraction, conversion and utilization of minerals and fuels, c) the ability to carry out experiments, interpret data and apply the results to the design and operation of engineering systems, and d) an understanding of the human, societal and economic issues involved in industrial activity and environmental protection.[ENGINEERING] ", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Environmental Sciences", " This program focuses on atmospheric science, hydrology, geology, ecology, environmental chemistry, and land and resource analysis. As an interdisciplinary field, environmental sciences also requires some knowledge from other disciplines such biology, chemistry, computer science, mathematics, and economics.<br />
After graduating, majors may find jobs in consulting, government agencies, forestry and agricultural firms, lobbying, and weather forecasting.[ENVIRONMENTAL RESOURCE MANAGEMENT/ SCIENCE]", "MATHEMATICS, PHYSICAL SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Environmental Resource Management", " This major has a broad foundation in communications and the biological, physical and social sciences. Issues associated with the management and sustainability of the environment may also be addressed from a scientific, social and political perspective. Courses may include ecosystem management, environmental law, pollutant impacts, resource economics, soil characterization, systems analysis and water management. Students may chose to specialize in any number of areas including ecology, energy and air pollution control, environmental education, environmental geography, environmental health, environmental toxicology, resource economics and policy, soil resources, and water resources.[ENVIRONMENTAL RESOURCE MANAGEMENT]", "GEOMETRY, AGRICULTURAL SCIENCE, LIFE SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Film and Video", "This major is designed to serve students whose major interest is the art of film and video practice. It serves students with professional objectives in the film, television, or related industries, as well as students planning to continue work in film and video on the graduate level. Courses of study may combine film/video production, directing, and screenwriting with history, criticism, and theory.[ART AND ARCHITECTURE/ COMMUNICATION ARTS] ", "ENGLISH, TOURISM");
$object->insertIntoTableCareer($conn, "Finance", " The role of the financial manager includes meeting corporate objectives, including financial planning and control, and raising and investing funds. Careers may include corporate finance, financial counseling, investment management, and banking.[BUSINESS]", "ACCOUNTING, ENGLISH");
$object->insertIntoTableCareer($conn, "Food Science", " Food scientists apply principles of chemistry, physics, and microbiology to food processing, preservation, and product development. The food science program provides students with a foundation in calculus, chemistry, physics, communications, statistics, and biology. The coursework generally centers around food engineering/processing, food chemistry, food microbiology, and food quality.[FOOD-LIFE SCIENCE]", "MATHEMATICS, PHYSICAL SCIENCE, LIFE SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Forest Science", "The Forest Science major is designed to help students develop the knowledge, skills, and professional ethics for understanding and managing forest ecosystems and living as responsible members of society. 
The Forest Science major provides for the education necessary for students to pursue professional careers in any one of the following options: forest biology, forest management, urban forestry, or watershed management. These options also will help prepare students for graduate studies in continuing professional education.[ENVIRONMENTAL RESOURCE MANAGEMENT] ", "MATHEMATICS, PHYSICAL SCIENCE, LIFE SCIENCE, ENGLISH");
$object->insertIntoTableCareer($conn, "Forest Technology", " The objectives of the major are to train forestry field personnel in the technical aspects of evaluating, managing, and protecting forest resources.
Graduates of the program may be employed by businesses including federal and state timber management and recreation programs, urban tree service companies, pulp and paper manufacturers, surveying and landscaping firms, power companies, and other businesses requiring personnel skilled in field data-gathering analysis and presentation. <strong>[ENVIRONMENTAL RESOURCE MANAGEMENT]", "LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "General Science", "This interdisciplinary major aims to provide a broad, general education in science.<br />
Students will likely have to complete some of the foundation courses in calculus, chemistry, physics, and the life sciences. Many students use this major to prepare for graduate school, professional schools, or employment in science-related disciplines.[SCIENCE] ", "PHYSICAL SCIENCE, LIFE SCIENCE");

$object->insertIntoTableCareer($conn, "Geography", "Geographers describe, analyze, and explain patterns of physical and human phenomena on the Earth's surface. Geography is simultaneously an environmental science and a social-behavioral science. This major helps provide grounding in analytical techniques such as map reading, cartography, and statistics. Substantive course work investigates the ways people use environmental resources and how they arrange themselves and their economic, social, and political activities on the earth's surface.<br />
The Geography major can provide preparation for a career in business, industry, or government. Geographers with bachelor's degrees may find placement in federal, state, and local administrative and planning agencies or in private firms that specialize in planning and development or in environmental and socioeconomic analysis.[SOCIAL SCIENCE] ", "GEOMETRY, LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Geosciences", "The geosciences are concerned with understanding earth processes and the evolutionary history of the Earth. Geoscientists work to discover and develop natural resources such as groundwater, metals, and energy sources; to solve technology-generated environmental problems such as acid mine drainage and waste disposal; to predict geological events, such as the occurrence of earthquakes and volcanism; and to solve fundamental questions concerning the origin and evolution of Earth and life. The Bachelor of Arts degree program stresses data collection, investigation, analysis and synthesis of information related to complex natural problems. Examples of these careers include environmental law, national and international planning or resource management, and teaching.[SOCIAL SCIENCE] ", "MATHEMATICS, PHYSICAL SCIENCE, LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Graphic Design and Photography", " Graphic design helps prepare students for employment in design studios, in advertising agencies, for publications, for film and television graphics, and as corporate designers. Photography helps prepare students for careers in commercial photography studios and in fashion, product, publications, industrial, architectural, and corporate photography.[ART AND ARCHITECTURE]", "ENGLISH, TOURISM");

$object->insertIntoTableCareer($conn, "Health and Physical Education", "The purpose of Physical Education, Health and Athletics is to provide a challenging curriculum leading to the development of abilities and convictions in a student's field of concentration. Students learn to develop the ability to utilize constructively all of his/her potential capacities for movement and movement education. There are many concentrations areas, such as exercise science/sports medicine, wellness and health promotion, or physical education. [<strong>ENVIRONMENTAL RESOURCE MANAGEMENT / EDUCATION/ HEALTH, PHYSICAL EDUCATION, AND RECREATION] ", "LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Health Policy and Administration", " This major helps prepare students for management and policy positions or graduate study in the field of health care. Students in the major develop the skills and knowledge needed to understand the complex societal problem of providing access to quality health care at reasonable cost. Students may obtain work in many health care organizations including hospitals, physician practices, nursing facilities, home health agencies, health maintenance organizations, insurers, and pharmaceutical companies. Some graduates may find work in policy positions for state and federal government, trade associations, and policy research organizations. The degree may also be used to prepare for graduate study in business, law, medicine or allied health fields, health administration, health services research, and public health. <strong>[ENVIRONMENTAL RESOURCE MANAGEMENT/ HEALTH SERVICES AND SCIENCES/ BUSINESS]", "LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "History", " History examines the human experience from its origins to the present. The history of countries such as Europe, Canada, America, China, Japan, India, Africa, or Latin America may be studied. Focus may be placed on public events of political, diplomatic, and constitutional history, or on the examination the social, cultural, or economic history of subjects such as villages, cities, witchcraft, sex, literacy, and work. History majors may go on to graduate school, law school or business school. Some may go into the work force, finding jobs with multinational corporations, governmental agencies, or small businesses.[SOCIAL SCIENCE]", "ENGLISH, HISTORY");

$object->insertIntoTableCareer($conn, "Horticulture", " From roses to turf, from greenhouses to landscape design, the horticulture diploma program covers everything students need to know about producing and marketing fruits, vegetables and ornamentals. Horticulture students will combine knowledge of the latest in plant production techniques with a solid foundation in management and finance. The result is responsible entrepreneurship in plant management.[ENVIRONMENTAL RESOURCE MANAGEMENT/ FOOD-LIFE SCIENCE]", "HISTORY, ENGLISH");

$object->insertIntoTableCareer($conn, "Hotel, Restaurant, and Institutional Management", "This major helps provide preparation for management positions in hotels, restaurants, institutions, and other hospitality organizations. The program is designed to give the student a broad general education and a strong management and problem solving orientation balanced with the requisite technical skills, all of them essential for career progression to upper-management positions in the hospitality professions. The program also helps prepare students for graduate study.[AGRIBUSINESS AND ECONOMICS/ BUSINESS] ", "ENGLISH, TOURISM");

$object->insertIntoTableCareer($conn,  "Human Development and Family Studies", "This major is a multidisciplinary program that examines the development of individuals and families across the life span. 
It enables students to prepare for professional, managerial, or scientific roles in health and human services professions, in public and nonprofit agencies, and in business and industry, as well as for advanced professional or graduate study. Students obtain a broad background in individual and family development across the life span. There are many areas of interest a student may select within this major. For example, the children, youth, and family service area focuses on the biological, psychological, and social development of infants, children, and adolescents, with special emphasis on the structure and functioning of the family. Typical employment settings include preschools, daycare centers, hospitals, institutional and community programs for emotionally disturbed, and abused or neglected children and adolescents, as well as a variety of public welfare and family service agencies.[BEHAVIORAL SCIENCE/ HUMAN SERVICES] ", "LIFE SCIENCE, ENGLISH");

$object->insertIntoTableCareer($conn, "Hydrology", "The program that focuses on the scientific study of the occurrence, circulation, distribution,
chemical and physical properties, and environmental interaction of surface and subsurface waters,
including groundwater. Includes instruction in geophysics, thermodynamics, fluid mechanics, 
chemical physics, geomorphology, mathematical modeling, hydrologic analysis, continental water processes,
global water balance, and environmental science. Possible jobs include Hydrology Professor, Hydrology Teacher, Hydrology Technician, Hydrologist, and Atmospheric Scientists[HYDROLOGY SCIENCE] ", "MATHEMATICS, PHYSICAL SCIENCE, LIFE SCIENCE, ENGLISH");


?>